export const SOUGHT_CRIME_STATS = 'SOUGHT_CRIME_STATS';
export const LOAD_CRIME_STATS = 'LOAD_CRIME_STATS';
export const SEARCH_CENTER = 'SEARCH_CENTER';

export const INITIAL_FILTER_LOADING = 'INITIAL_FILTER_LOADING';
export const FILTER_CRIMES = 'FILTER_CRIMES';

export const TRUE_CRIME_CALL = 'TRUE_CRIME_CALL';
export const FALSE_CRIME_CALL = 'FALSE_CRIME_CALL';

export const CITY_INFO_LOAD = 'CITY_INFO_LOAD';
